function ready(){
	 //   lang = (jQuery.i18n.browserLang().substring(0,2));检测浏览器当前语言环境
	 		var lang = localStorage.getItem('lang');
	 		if(lang==null){
		    	lang = (jQuery.i18n.browserLang().substring(0,2));//检测浏览器当前语言环境
		    }
	 	 
			jQuery.i18n.properties({
				name:'strings',
				path:'../../i18n/',
				mode:'map',
				language:lang,
				callback:function(){ 
					$('#ribao').html($.i18n.prop('ribao')); 
					$('#zhoubao').html($.i18n.prop('zhoubao'));
					$('#qingshi').html($.i18n.prop('qingshi'));
					$('#qiandao').html($.i18n.prop('qiandao'));
					$('#gongsigonggao').html($.i18n.prop('gongsigonggao'));
					$('#gongsiggtext').html($.i18n.prop('gongsigonggao'));
					$('#tupian').html($.i18n.prop('tupian'));
					$('#wenzhang').html($.i18n.prop('wenzhang'));
					$('#fanhui').html($.i18n.prop('fanrhui'));
					$('#gongsiwenzhang').html($.i18n.prop('gongsiwenzhang'));
					$('#xiangqing').html($.i18n.prop('xiangqing')); 
					$('#xinzen').html($.i18n.prop('xinzen')); 
					$('#xiangce').html($.i18n.prop('xiangce')); 
					$('#paizhao').html($.i18n.prop('paizhao')); 
					$('#pinglun').html($.i18n.prop('pinglun')); 
					$('#saoyisao').html($.i18n.prop('saoyisao')); 
					$('#wodemingpian').html($.i18n.prop('wodemingpian')); 
					$('#wodedongtai').html($.i18n.prop('wodedongtai')); 
					$('#sousuohaoyou').html($.i18n.prop('sousuohaoyou')); 
					$('#shezhi').html($.i18n.prop('shezhi')); 
					$('#jieshouren').html($.i18n.prop('jieshouren')); 
					$('#jiezhishijian').html($.i18n.prop('jiezhishijian')); 
					$('#leixing').html($.i18n.prop('leixing')); 
					$('#tixingshixiang').html($.i18n.prop('tixingshixiang')); 
					$('#caiwu').html($.i18n.prop('caiwu')); 
					$('#jishiben').html($.i18n.prop('jishiben')); 
					$('#shenpi').html($.i18n.prop('shenpi'));    
					$('#shenpi').html($.i18n.prop('shenpi')); 
					$('#gerenzhongxin').html($.i18n.prop('gerenzhongxin'));   
					$('#touxiang').html($.i18n.prop('touxiang'));   
					$('#mingzi').html($.i18n.prop('mingzi'));   
					$('#eworkid').html($.i18n.prop('eworkid')); 
					$('#xingbie').html($.i18n.prop('xingbie'));   
					$('#shengri').html($.i18n.prop('shengri'));   
					$('#gexingqianming').html($.i18n.prop('gexingqianming'));   
					$('#yiwancheng').html($.i18n.prop('yiwancheng'));  
					$('#weiwancheng').html($.i18n.prop('weiwancheng'));  
					$('#xuxietiao').html($.i18n.prop('xuxietiao'));   
					$('#beizhu').html($.i18n.prop('beizhu'));     
					$('#miaoshu').html($.i18n.prop('miaoshu'));  
					$('#shijian').html($.i18n.prop('shijian'));  
					$('#didian').html($.i18n.prop('didian'));  
					$('#fabuzhe').html($.i18n.prop('fabuzhe')); 
					$('#biaoti').html($.i18n.prop('biaoti')); 
					$('#liyou').html($.i18n.prop('liyou'));
					$('#kaishishijian').html($.i18n.prop('kaishishijian'));
					$('#jieshushijian').html($.i18n.prop('jieshushijian')); 
					$('#tianshu').html($.i18n.prop('tianshu')); 
					$('#jine').html($.i18n.prop('jine')); 
					$('#piaojuzhangshu').html($.i18n.prop('piaojuzhangshu')); 
		 		    $('#tongguo').html($.i18n.prop('tongguo')); 
		 		    $('#weitongguo').html($.i18n.prop('weitongguo')); 
		 		    $('#yuyan').html($.i18n.prop('yuyan')); 
		 		    $('#hanyu').html($.i18n.prop('hanyu')); 
		 		    $('#yingyu').html($.i18n.prop('yingyu')); 
		 		    $('#riyu').html($.i18n.prop('riyu')); 
		 		    $('#zhuxiao').html($.i18n.prop('zhuxiao')); 
		 		    $('#jujue').html($.i18n.prop('jujue')); 
		 		    $('#shenpizhong').html($.i18n.prop('shenpizhong')); 
				}
			});
		}